<a href="https://colab.research.google.com/github/Vicrrs/Sklearn_classification/blob/main/MachineLearning_Classifica%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install scikit-learn



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Importando os dados

In [2]:
import pandas as pd

In [3]:
dados = pd.read_csv('/content/base.csv')

In [4]:
# linhas/colunas
dados.shape

(7043, 18)

In [5]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

Variaveis Categoricas - Agrupamento por caracteristicas em comum. Agrupamento por valores qualitativos.

Variaveis númericas - Representa uma medida ou um conjunto infinito de valores

## Diferentes Variáveis

In [6]:
#modificação  dde forma manual
traducao_dic = {'Sim' : 1,
                'Nao' : 0}

dadosmodificados = dados[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao_dic)
dadosmodificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [7]:
# transformação pelo getdummies
dummie_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis=1))
#junção dos dados transformandos com os que já tinham
dados_final = pd.concat([dadosmodificados, dummie_dados], axis=1)

In [8]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   
3                                             1  ...                      1   
4                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 39 columns]

In [9]:
dados_final.shape

(7043, 39)

## Definição formal de classificação classificação

Informações para classificação:

X = inputs (dados de entrada)

y = outputs (dados de saída)

In [10]:
#DICA

pd.set_option('display.max_columns', 39)

In [11]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   
3                      1                              0   
4                      0                              1   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                      0                    1   
1                      0                    0   
2                      0                    0   
3                      0                    0   
4                      0                    1   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                     0                    0   
1                                     0                    1   
2                                     0                    1   
3                                     0                    1   
4                                     0                    0   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0                 0                                  0                 1   
1                 1                                  0                 0   
2                 0                                  0                 1   
3                 1                                  0                 0   
4                 1                                  0                 0   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                        1                                         0   
1                        0                                         0   
2                        1                                         0   
3                        0                                         0   
4                        1                                         0   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                        0                   1   
1                        1                   1   
2                        0                   1   
3                        1                   0   
4                        0                   1   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                    0                   0            1   
1                                    0                   0            1   
2                                    0                   0            1   
3                                    0                   1            1   
4                                    0                   0         

y = f(x)

## KNN por trás dos panos

In [12]:
Xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,0,0,0,1,1,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,1, 0, 1, 1]]


In [13]:
Xmaria

[[0,
  0,
  1,
  1,
  0,
  0,
  39.9,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1]]

In [14]:
#ymaria = 

In [15]:
#biblioteca para padronização de dados
from sklearn.preprocessing import StandardScaler

In [16]:
#Divisão em inputs e outputs
X = dados_final.drop('Churn', axis=1)
Y = dados_final['Churn']

In [17]:
norm = StandardScaler()

X_normalizado = norm.fit_transform(X)
X_normalizado

array([[ 1.03453023, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 , -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
        -0.54480692,  1.88720123]])

In [18]:
X_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [19]:
Xmaria_normalizado = norm.transform(pd.DataFrame(Xmaria, columns = X.columns))
Xmaria_normalizado

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737, -0.99334883, -0.52592737,
        -0.63393298,  1.13170855,  1.90140322,  1.3782406 , -0.88540456,
        -0.52592737,  1.38127743,  1.0138687 , -0.52592737, -0.63943864,
        -0.81475874, -0.52592737,  1.26561178, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 , -0.51424938,  1.90459021,
        -0.71102597,  1.83551265,  1.88720123]])

Distânca Euclidiana

In [20]:
import numpy as np

In [21]:
a = Xmaria_normalizado

In [22]:
b = X_normalizado[0]

In [23]:
# 1º começamos subtraindo
a - b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -0.04072036,  0.3340212 ,  2.00139589, -3.3814487 ,  0.        ,
        -2.10545189,  2.01476153,  0.        , -2.00004453,  0.        ,
         0.        ,  2.01532828,  2.42733059,  0.        , -2.01483177,
         0.        ,  2.10524495,  0.        ,  0.        ,  0.        ,
        -2.04211593,  0.        ,  2.05574349, -2.0452305 ,  0.        ,
         2.05224086,  0.        , -2.01015362,  0.        ,  2.42963754,
        -2.11744436,  2.38031958,  2.41708643]])

In [24]:
#2º depois realizamos a exponenciação
np.square(a-b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.65814802e-03, 1.11570160e-01, 4.00558550e+00,
        1.14341953e+01, 0.00000000e+00, 4.43292768e+00, 4.05926401e+00,
        0.00000000e+00, 4.00017814e+00, 0.00000000e+00, 0.00000000e+00,
        4.06154807e+00, 5.89193381e+00, 0.00000000e+00, 4.05954705e+00,
        0.00000000e+00, 4.43205631e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.17023749e+00, 0.00000000e+00, 4.22608130e+00,
        4.18296779e+00, 0.00000000e+00, 4.21169253e+00, 0.00000000e+00,
        4.04071758e+00, 0.00000000e+00, 5.90313856e+00, 4.48357062e+00,
        5.66592128e+00, 5.84230682e+00]])

In [25]:
#3º a soma
np.sum(np.square(a-b))

104.65590496901619

In [26]:
#4º então tiramos a raiz e temos nossa distância
np.sqrt(104.65590496901619)

10.230146869376616

## Implementando o modelo

In [27]:
#biblioteca para divisão de dados
from sklearn.model_selection import train_test_split

In [28]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X_normalizado, Y, test_size=0.3, random_state=123)

##Treinamento e teste

In [29]:
#biblioteca para criarmos o modelo de machinlearninf 
from sklearn.neighbors import KNeighborsClassifier

In [30]:
#instanciar o modelo (criamos o modelo) - por padrao sao 5 vizinhos
knn = KNeighborsClassifier(metric='euclidean')


In [31]:
#treinando o modelo com os dados do modelo
knn.fit(X_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [32]:
#testando o modelo com os dados de teste
predito_knn = knn.predict(X_teste)

In [33]:
predito_knn

array([1, 0, 0, ..., 0, 0, 0])

In [34]:
X_treino

array([[-0.96662231, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023,  1.5290241 , -3.05401039, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ]])

In [35]:
y_treino

1479    0
2377    0
6613    0
6468    0
2668    1
       ..
5218    0
4060    0
1346    1
3454    0
3582    0
Name: Churn, Length: 4930, dtype: int64

In [36]:
#escolho utilizar mediana, pq é o valor central dos nossos dados ordendados
np.median(X_treino)

-0.5259273725834717

In [37]:
#biblioteca para criarmos o modelo de machine learning
from sklearn.naive_bayes import BernoulliNB

In [38]:
#criamo o modelo
bnb = BernoulliNB(binarize=-0.52)

In [39]:
bnb.fit(X_treino, y_treino)

BernoulliNB(binarize=-0.52)

In [40]:
predito_BNb = bnb.predict(X_teste)

In [41]:
predito_BNb

array([1, 0, 0, ..., 0, 1, 0])

##Implementando o modelo

In [43]:
#biblioteca para criarmo o modelo de machine learning
from sklearn.tree import DecisionTreeClassifier

In [44]:
#instanciando o modelo
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)

In [45]:
#treinar o modelo
dtc.fit(X_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [46]:
#verificar a importancia de cade atributo
dtc.feature_importances_

array([0.03168742, 0.01862901, 0.00064085, 0.02675693, 0.0208788 ,
       0.2056003 , 0.29546501, 0.0061786 , 0.00273035, 0.00747536,
       0.        , 0.04908356, 0.        , 0.01609395, 0.        ,
       0.00722833, 0.01220706, 0.        , 0.01248286, 0.01138295,
       0.0006673 , 0.0095669 , 0.01841631, 0.        , 0.00650511,
       0.00385849, 0.        , 0.00666929, 0.00517146, 0.        ,
       0.00665371, 0.00473251, 0.15803541, 0.00348686, 0.01414378,
       0.01601964, 0.01064163, 0.01091026])

In [47]:
predito_ArvoreDecisao = dtc.predict(X_teste)

In [48]:
predito_ArvoreDecisao

array([1, 0, 0, ..., 1, 0, 0])

## Validação do modelo

### Matriz de confusão

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
print(confusion_matrix(y_teste, predito_knn))

[[1302  221]
 [ 317  273]]


In [52]:
print(confusion_matrix(y_teste, predito_BNb))

[[1045  478]
 [ 117  473]]


In [53]:
print(confusion_matrix(y_teste, predito_ArvoreDecisao))

[[1249  274]
 [ 290  300]]


###Acurácia

In [54]:
from sklearn.metrics import accuracy_score

In [55]:
#modelo KNN
print(accuracy_score(y_teste, predito_knn))

0.7453857075248462


In [56]:
#modelo Bernoulli Naive Bayes
print(accuracy_score(y_teste, predito_BNb))

0.718409843823947


In [57]:
#modelo árvore de decisão
print(accuracy_score(y_teste, predito_ArvoreDecisao))

0.7330809275911027


### Precisão

In [58]:
from sklearn.metrics import precision_score

In [59]:
#modelo KNN
print(precision_score(y_teste, predito_knn))

0.5526315789473685


In [60]:
#modelo Bernoulli Naive Bayes
print(precision_score(y_teste, predito_BNb))

0.49737118822292326


In [61]:
#modelo árvore de decisão
print(precision_score(y_teste, predito_ArvoreDecisao))

0.5226480836236934


###Recall

In [62]:
from sklearn.metrics import recall_score

In [63]:
#modelo KNN
print(recall_score(y_teste, predito_knn))

0.46271186440677964


In [64]:
#modelo Bernoulli Naive Bayes
print(recall_score(y_teste, predito_BNb))

0.8016949152542373


In [65]:
#modelo árvore de decisão
print(recall_score(y_teste, predito_ArvoreDecisao))

0.5084745762711864


## Escolhendo a melhor métrica

In [66]:
print('Modelo KNN:', precision_score(y_teste, predito_knn))
print('Modelo Bernoulli de Naive Bayes:', precision_score(y_teste, predito_BNb))
print('Modelo Àrvore de Decisão:', precision_score(y_teste, predito_ArvoreDecisao))


Modelo KNN: 0.5526315789473685
Modelo Bernoulli de Naive Bayes: 0.49737118822292326
Modelo Àrvore de Decisão: 0.5226480836236934
